# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Deploy to Container App

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build:
    name: Build and test solution
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies dotnet
      run: dotnet restore
    
    - name: Build with dotnet
      run: dotnet build --no-restore
    
    - name: Test dotnet
      run: dotnet test --no-build --verbosity normal

    - name: Get Latest Container Image Tag
      id: get_tag
      run: |
        TAG=$(az acr repository show-tags --name myacrmicrohackday --repository mywebapp-microhack-day --orderby time_desc --output tsv --detail | head -n 1 | awk '{print $4}')
        NUMERIC_TAG=$(echo "$TAG" | grep -oE '[0-9]+')
        INCREMENTED_TAG=$((NUMERIC_TAG + 1))
        UPDATED_TAG=$(echo "$TAG" | sed "s/$NUMERIC_TAG/$INCREMENTED_TAG/")
        echo "image_tag=$UPDATED_TAG" >> $GITHUB_OUTPUT
        
    - name: Build and Push Image
      run: |
        az acr login --name myacrmicrohackday --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }} &&
        docker build -t myacrmicrohackday.azurecr.io/mywebapp-microhack-day:${{ steps.get_tag.outputs.image_tag }} -f Dockerfile . &&
        docker push myacrmicrohackday.azurecr.io/mywebapp-microhack-day:${{ steps.get_tag.outputs.image_tag }}

    - name: Deploy to Container App
      uses: azure/container-apps-deploy-action@v2
      with:
        imageToDeploy: myacrmicrohackday.azurecr.io/mywebapp-microhack-day:${{ steps.get_tag.outputs.image_tag }}
        acrUsername: ${{ secrets.ACR_USERNAME }}
        acrPassword: ${{ secrets.ACR_PASSWORD }}
        resourceGroup: MicroHack-AppServiceToContainerApp
        containerAppEnvironment: mycontainerappenvironment
        containerAppName: mycontainerapp
        targetPort: 8080
        environmentVariables: |
                  API_URL=https://mycontainer-aiapp.blackfield-cf218aab.westeurope.azurecontainerapps.io
